PHP=hhvm
#PHP=php

test: getChristmasDay isAdditionalDay isDate isEasterMonday isGoodFriday isLabourDay isQueensBirthday


getChristmasDay: getChristmasDay.php
	$(PHP) getChristmasDay.php

isAdditionalDay: isAdditionalDay.php
	$(PHP) isAdditionalDay.php

isDate: isDate.php
	$(PHP) isDate.php

isEasterMonday: isEasterMonday.php
	$(PHP) isEasterMonday.php

isGoodFriday: isGoodFriday.php
	$(PHP) isGoodFriday.php

isLabourDay: isLabourDay.php
	$(PHP) isLabourDay.php

isQueensBirthday: isQueensBirthday.php
	$(PHP) isQueensBirthday.php
